if(EXISTS "D:/forWork/projects/C++ - Standart/SearchEngine/Search_Engine/examples/test_search_engine/test/tests[1]_tests.cmake")
  include("D:/forWork/projects/C++ - Standart/SearchEngine/Search_Engine/examples/test_search_engine/test/tests[1]_tests.cmake")
else()
  add_test(tests_NOT_BUILT tests_NOT_BUILT)
endif()
